# -*- coding: utf-8 -*-
"""Streamlit UI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MIKmoRPMm8DhgmCKIpodv4r9Oun48ELv
"""

import streamlit as st
from PIL import Image
import random

st.set_page_config(
    page_title="SafeSight",
    page_icon="🎯",
    layout="wide",
    initial_sidebar_state="collapsed"
)

st.markdown("""
<link href="https://fonts.googleapis.com/css2?family=Pretendard:wght@400;500;600;700;800&display=swap" rel="stylesheet">
<style>
*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }

html, body, [class*="css"], .stApp {
    font-family: 'Pretendard', 'Apple SD Gothic Neo', sans-serif;
    background: #F2F4FA !important;
}

/* ── Hide Streamlit chrome ── */
#MainMenu, footer, header { visibility: hidden; }
.block-container { padding: 0 !important; max-width: 100% !important; }
section[data-testid="stSidebar"] { display: none; }

/* ── Top nav ── */
.ss-nav {
    background: #12193A;
    padding: 0 40px;
    height: 64px;
    display: flex;
    align-items: center;
    justify-content: space-between;
    position: sticky;
    top: 0;
    z-index: 100;
}
.ss-brand {
    display: flex;
    align-items: center;
    gap: 12px;
    color: #fff;
    font-size: 20px;
    font-weight: 800;
    letter-spacing: -0.5px;
}
.ss-brand-icon {
    width: 36px; height: 36px;
    background: #2E4BD6;
    border-radius: 10px;
    display: flex; align-items: center; justify-content: center;
    font-size: 18px;
}
.ss-nav-links { display: flex; gap: 32px; align-items: center; }
.ss-nav-link { color: #8899CC; font-size: 14px; font-weight: 500; text-decoration: none; }
.ss-nav-link.active { color: #fff; }
.ss-nav-bell {
    width: 36px; height: 36px;
    border: 1.5px solid #2a3660;
    border-radius: 10px;
    display: flex; align-items: center; justify-content: center;
    color: #8899CC;
    font-size: 16px;
    cursor: pointer;
}

/* ── Page shell ── */
.ss-page { display: flex; min-height: calc(100vh - 64px); }

/* ── Sidebar ── */
.ss-sidebar {
    width: 260px;
    background: #fff;
    border-right: 1px solid #E8EAF2;
    padding: 28px 20px;
    flex-shrink: 0;
}
.ss-sidebar-title { font-size: 11px; font-weight: 700; color: #AAB0CC; letter-spacing: 1px; text-transform: uppercase; margin-bottom: 10px; }
.ss-sidebar-item {
    display: flex;
    align-items: center;
    gap: 10px;
    padding: 10px 12px;
    border-radius: 10px;
    font-size: 14px;
    font-weight: 500;
    color: #555;
    cursor: pointer;
    margin-bottom: 4px;
    transition: all 0.15s;
}
.ss-sidebar-item.active { background: #EEF1FF; color: #2E4BD6; font-weight: 600; }
.ss-sidebar-item:hover:not(.active) { background: #F5F6FA; }
.ss-sidebar-icon { font-size: 16px; }

/* ── Main content ── */
.ss-main { flex: 1; padding: 36px 40px; overflow-y: auto; }

/* ── Page title ── */
.ss-page-title { font-size: 26px; font-weight: 800; color: #12193A; letter-spacing: -0.5px; margin-bottom: 4px; }
.ss-page-sub { font-size: 14px; color: #8899AA; margin-bottom: 28px; }

/* ── Search card ── */
.ss-card {
    background: #fff;
    border-radius: 16px;
    border: 1px solid #E8EAF0;
    padding: 28px;
    margin-bottom: 20px;
}
.ss-card-title { font-size: 13px; font-weight: 700; color: #12193A; margin-bottom: 12px; letter-spacing: 0.2px; }

/* ── Text input override ── */
.stTextInput > div > div > input {
    border: 1.5px solid #E0E3EE !important;
    border-radius: 12px !important;
    padding: 12px 16px !important;
    font-size: 14px !important;
    font-family: 'Pretendard', sans-serif !important;
    background: #F9FAFC !important;
    color: #12193A !important;
    transition: border 0.2s !important;
}
.stTextInput > div > div > input:focus {
    border-color: #2E4BD6 !important;
    box-shadow: 0 0 0 3px rgba(46,75,214,0.08) !important;
}

/* ── File uploader ── */
.stFileUploader > div {
    border: 2px dashed #D4D8EE !important;
    border-radius: 14px !important;
    background: #F7F8FD !important;
    padding: 24px !important;
}

/* ── Divider ── */
.ss-or { display: flex; align-items: center; gap: 12px; margin: 14px 0; color: #AABCC0; font-size: 12px; }
.ss-or::before, .ss-or::after { content: ''; flex: 1; height: 1px; background: #E8EAF2; }

/* ── Filter chips ── */
.ss-chip-row { display: flex; gap: 8px; flex-wrap: wrap; margin-bottom: 4px; }

/* ── Buttons ── */
.stButton > button {
    border-radius: 12px !important;
    font-family: 'Pretendard', sans-serif !important;
    font-weight: 600 !important;
    font-size: 14px !important;
    transition: all 0.2s !important;
}
button[kind="primary"], .stButton > button[data-testid*="primary"] {
    background: #12193A !important;
    color: #fff !important;
    border: none !important;
    padding: 12px 24px !important;
}

/* ── Result grid ── */
.result-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 16px; }
.result-card {
    background: #fff;
    border-radius: 16px;
    border: 1.5px solid #E8EAF0;
    overflow: hidden;
    cursor: pointer;
    transition: box-shadow 0.2s, transform 0.2s;
}
.result-card:hover { box-shadow: 0 8px 24px rgba(18,25,58,0.10); transform: translateY(-2px); }
.result-img {
    height: 160px;
    background: linear-gradient(135deg, #DDE2F4 0%, #C9D0EE 100%);
    display: flex; align-items: center; justify-content: center;
    font-size: 64px;
    position: relative;
}
.result-badge {
    position: absolute;
    top: 10px; right: 10px;
    background: #12193A;
    color: #fff;
    font-size: 11px;
    font-weight: 700;
    padding: 4px 10px;
    border-radius: 20px;
}
.result-badge.high { background: #2E4BD6; }
.result-badge.mid { background: #22A06B; }
.result-badge.low { background: #E25C1C; }
.result-body { padding: 14px 16px; }
.result-id { font-size: 12px; font-weight: 700; color: #2E4BD6; margin-bottom: 3px; }
.result-loc { font-size: 12px; color: #99A0B8; margin-bottom: 8px; }
.result-tags { display: flex; gap: 5px; flex-wrap: wrap; margin-bottom: 10px; }
.rtag {
    padding: 3px 9px;
    border-radius: 8px;
    font-size: 11px;
    font-weight: 600;
    background: #EEF1FF;
    color: #2E4BD6;
}
.rtag.acc { background: #FEEADB; color: #C24E0F; }
.rtag.loc { background: #E3F5EC; color: #1A7A4A; }
.sim-row { display: flex; align-items: center; gap: 8px; }
.sim-bar-bg { flex: 1; background: #EEF0F8; border-radius: 4px; height: 6px; }
.sim-bar { height: 6px; border-radius: 4px; background: #2E4BD6; }
.sim-pct { font-size: 12px; font-weight: 700; color: #2E4BD6; min-width: 32px; text-align: right; }

/* ── Detail panel ── */
.detail-panel {
    background: #fff;
    border-radius: 16px;
    border: 1px solid #E8EAF0;
    overflow: hidden;
}
.detail-img {
    height: 240px;
    background: linear-gradient(135deg, #DDE2F4 0%, #C9D0EE 100%);
    display: flex; align-items: center; justify-content: center;
    font-size: 100px;
    position: relative;
}
.detail-ai-badge {
    position: absolute;
    top: 14px; left: 14px;
    background: #2E4BD6;
    color: #fff;
    font-size: 12px;
    font-weight: 700;
    padding: 5px 12px;
    border-radius: 8px;
}
.bbox-overlay {
    position: absolute;
    border: 3px solid #2E4BD6;
    border-radius: 6px;
    width: 160px; height: 130px;
}
.detail-body { padding: 24px; }
.detail-sim-label { display: flex; justify-content: space-between; font-size: 12px; color: #99A0B8; margin-bottom: 6px; }
.detail-sim-label span:last-child { color: #2E4BD6; font-weight: 700; font-size: 14px; }
.detail-bar-bg { background: #EEF0F8; border-radius: 6px; height: 8px; margin-bottom: 20px; }
.detail-bar { background: linear-gradient(90deg, #2E4BD6, #5B8BFF); height: 8px; border-radius: 6px; }
.detail-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; margin-bottom: 20px; }
.detail-cell {
    background: #F7F8FC;
    border-radius: 10px;
    padding: 12px 14px;
    border: 1px solid #ECEEF6;
}
.dc-label { font-size: 11px; color: #AAB2CC; margin-bottom: 4px; font-weight: 500; }
.dc-value { font-size: 15px; font-weight: 700; color: #12193A; }
.found-section { margin-bottom: 20px; }
.found-title { font-size: 13px; font-weight: 700; color: #12193A; margin-bottom: 6px; }
.found-text { font-size: 13px; color: #667; line-height: 1.75; }
.action-btns { display: flex; gap: 10px; }
.btn-primary {
    flex: 2;
    background: #12193A;
    color: #fff;
    border: none;
    border-radius: 12px;
    padding: 13px 0;
    font-size: 14px;
    font-weight: 700;
    cursor: pointer;
    text-align: center;
}
.btn-secondary {
    flex: 1;
    background: #F2F4FA;
    color: #12193A;
    border: 1.5px solid #E0E3EE;
    border-radius: 12px;
    padding: 13px 0;
    font-size: 14px;
    font-weight: 600;
    cursor: pointer;
    text-align: center;
}

/* Recent tag */
.recent-tag {
    display: inline-flex;
    align-items: center;
    gap: 6px;
    background: #F0F2FA;
    color: #445;
    padding: 5px 12px;
    border-radius: 20px;
    font-size: 12px;
    font-weight: 500;
    cursor: pointer;
    margin-right: 6px;
    margin-bottom: 6px;
}
.section-divider { border: none; border-top: 1px solid #EEF0F8; margin: 24px 0; }

/* Stats bar */
.stats-bar {
    display: grid;
    grid-template-columns: repeat(4, 1fr);
    gap: 14px;
    margin-bottom: 24px;
}
.stat-card {
    background: #fff;
    border-radius: 14px;
    border: 1px solid #E8EAF0;
    padding: 18px 20px;
}
.stat-label { font-size: 12px; color: #99A0B8; font-weight: 500; margin-bottom: 6px; }
.stat-value { font-size: 24px; font-weight: 800; color: #12193A; letter-spacing: -0.5px; }
.stat-sub { font-size: 11px; color: #22A06B; font-weight: 600; margin-top: 2px; }
</style>
""", unsafe_allow_html=True)

# ── Session State ──
if "page" not in st.session_state:
    st.session_state.page = "search"
if "selected" not in st.session_state:
    st.session_state.selected = None
if "active_filter" not in st.session_state:
    st.session_state.active_filter = "전체"
if "query" not in st.session_state:
    st.session_state.query = ""
if "recent" not in st.session_state:
    st.session_state.recent = ["흰색 말티즈 빨간목줄", "갈색 푸들 하네스"]

MOCK = [
    {"id": "#2024-03871", "icon": "🐶", "loc": "서울 강남구", "time": "2일 전", "breed": "말티즈", "color": "흰색", "acc": "빨간 목줄", "score": 92, "tags": [("말티즈","", "흰색","", "빨간 목줄","acc")], "detail": "서울 강남구 역삼동 인근 CCTV에서 탐지됨. 목줄 착용, 중성화 여부 미확인. 현재 보호 중."},
    {"id": "#2024-03645", "icon": "🐕", "loc": "서울 송파구", "time": "4일 전", "breed": "믹스견", "color": "크림색", "acc": "없음", "score": 84, "tags": [("믹스견","", "크림색","" )], "detail": "송파구 잠실동 공원에서 발견. 목줄 미착용, 상태 양호. 임시 보호 중."},
    {"id": "#2024-03512", "icon": "🐩", "loc": "경기 하남시", "time": "1주일 전", "breed": "비숑", "color": "흰색", "acc": "없음", "score": 77, "tags": [("비숑","", "흰색","" )], "detail": "하남시 미사동 인근 주민 제보. 상태 보통, 치료 후 보호 중."},
]

# ── Navbar ──
st.markdown("""
<div class="ss-nav">
  <div class="ss-brand">
    <div class="ss-brand-icon">🎯</div>
    SafeSight
  </div>
  <div class="ss-nav-links">
    <a class="ss-nav-link active" href="#">탐색</a>
    <a class="ss-nav-link" href="#">제보하기</a>
    <a class="ss-nav-link" href="#">공고 관리</a>
    <a class="ss-nav-link" href="#">통계</a>
  </div>
  <div class="ss-nav-bell">🔔</div>
</div>
""", unsafe_allow_html=True)

# ── Page shell ──
left_col, main_col = st.columns([1, 4], gap="small")

with left_col:
    st.markdown("""
    <div class="ss-sidebar">
      <div class="ss-sidebar-title">메뉴</div>
      <div class="ss-sidebar-item active"><span class="ss-sidebar-icon">🔍</span> 인상착의 검색</div>
      <div class="ss-sidebar-item"><span class="ss-sidebar-icon">📸</span> 이미지 검색</div>
      <div class="ss-sidebar-item"><span class="ss-sidebar-icon">📋</span> 공고 목록</div>
      <div class="ss-sidebar-item"><span class="ss-sidebar-icon">⭐</span> 즐겨찾기</div>
      <div class="ss-sidebar-item"><span class="ss-sidebar-icon">📊</span> 통계 대시보드</div>
      <hr style="border:none;border-top:1px solid #EEF0F8;margin:16px 0;">
      <div class="ss-sidebar-title">설정</div>
      <div class="ss-sidebar-item"><span class="ss-sidebar-icon">⚙️</span> 환경설정</div>
      <div class="ss-sidebar-item"><span class="ss-sidebar-icon">🏥</span> 보호소 연결</div>
    </div>
    """, unsafe_allow_html=True)

with main_col:
    st.markdown('<div class="ss-main">', unsafe_allow_html=True)

    # ── Stats ──
    st.markdown("""
    <div class="stats-bar">
      <div class="stat-card">
        <div class="stat-label">총 공고 수</div>
        <div class="stat-value">1,284</div>
        <div class="stat-sub">▲ 이번 주 +38건</div>
      </div>
      <div class="stat-card">
        <div class="stat-label">매칭 성공</div>
        <div class="stat-value">342</div>
        <div class="stat-sub" style="color:#2E4BD6;">▲ 전월 대비 +12%</div>
      </div>
      <div class="stat-card">
        <div class="stat-label">평균 유사도</div>
        <div class="stat-value">87%</div>
        <div class="stat-sub">Top-5 Accuracy</div>
      </div>
      <div class="stat-card">
        <div class="stat-label">탐지 모델</div>
        <div class="stat-value" style="font-size:15px;padding-top:5px;">CLIP ViT-L/14</div>
        <div class="stat-sub" style="color:#99A0B8;">YOLOv8 연동</div>
      </div>
    </div>
    """, unsafe_allow_html=True)

    if st.session_state.page == "search":
        st.markdown('<div class="ss-page-title">유기동물 인상착의 탐색</div>', unsafe_allow_html=True)
        st.markdown('<div class="ss-page-sub">CLIP 기반 멀티모달 검색 · 자연어 또는 사진으로 유기동물을 찾아보세요</div>', unsafe_allow_html=True)

        st.markdown('<div class="ss-card">', unsafe_allow_html=True)
        st.markdown('<div class="ss-card-title">🔍 인상착의 입력</div>', unsafe_allow_html=True)
        query = st.text_input("", placeholder='"빨간 목줄을 착용한 흰색 말티즈" 처럼 구체적으로 입력하세요', key="q_input", label_visibility="collapsed")

        st.markdown('<div class="ss-or">또는</div>', unsafe_allow_html=True)

        st.markdown('<div class="ss-card-title">📸 사진 업로드</div>', unsafe_allow_html=True)
        uploaded = st.file_uploader("반려동물 사진을 업로드하면 AI가 유사한 개체를 탐색합니다", type=["jpg","jpeg","png"], key="photo")
        if uploaded:
            st.image(Image.open(uploaded), width=300, caption="업로드된 사진")
        st.markdown('</div>', unsafe_allow_html=True)

        # Filters
        st.markdown('<div class="ss-card">', unsafe_allow_html=True)
        st.markdown('<div class="ss-card-title">🗂️ 필터</div>', unsafe_allow_html=True)
        filters = ["전체", "강아지", "고양이", "서울", "경기", "인천", "부산"]
        cols = st.columns(len(filters))
        for i, f in enumerate(filters):
            with cols[i]:
                is_active = st.session_state.active_filter == f
                label = f"**{f}**" if is_active else f
                if st.button(label, key=f"f_{f}", use_container_width=True):
                    st.session_state.active_filter = f
                    st.rerun()
        st.markdown('</div>', unsafe_allow_html=True)

        # Recent
        if st.session_state.recent:
            st.markdown('<div class="ss-card-title" style="margin-bottom:8px;">🕐 최근 탐색</div>', unsafe_allow_html=True)
            recent_html = "".join(f'<span class="recent-tag">🔎 {r}</span>' for r in st.session_state.recent)
            st.markdown(f'<div>{recent_html}</div>', unsafe_allow_html=True)

        st.markdown("<br>", unsafe_allow_html=True)
        c1, c2, c3 = st.columns([3, 1, 1])
        with c1:
            if st.button("🔍  탐색 시작", type="primary", use_container_width=True):
                q = query or (uploaded.name if uploaded else "")
                st.session_state.query = q if q else "흰색 말티즈 빨간목줄"
                if st.session_state.query not in st.session_state.recent:
                    st.session_state.recent.insert(0, st.session_state.query)
                    st.session_state.recent = st.session_state.recent[:5]
                st.session_state.page = "results"
                st.rerun()
        with c2:
            if st.button("초기화", use_container_width=True):
                st.session_state.query = ""
                st.rerun()

    elif st.session_state.page == "results":
        bc1, bc2 = st.columns([1, 8])
        with bc1:
            if st.button("← 뒤로"):
                st.session_state.page = "search"
                st.rerun()
        with bc2:
            st.markdown(f'<div class="ss-page-title">검색 결과</div>', unsafe_allow_html=True)
            st.markdown(f'<div class="ss-page-sub">"{st.session_state.query}" · 총 {len(MOCK)}건 탐색됨 · 필터: {st.session_state.active_filter}</div>', unsafe_allow_html=True)

        # Sort/filter row
        sort_col, space = st.columns([2, 5])
        with sort_col:
            sort = st.selectbox("정렬", ["유사도 높은 순", "최근 발견순", "거리 가까운 순"], label_visibility="collapsed")

        st.markdown("<br>", unsafe_allow_html=True)

# Result cards as columns
        cols = st.columns(3)
        for i, item in enumerate(MOCK):
            with cols[i]:
                badge_cls = "high" if item["score"] >= 90 else "mid" if item["score"] >= 80 else "low"
                
                # ------ [🔥 튜플 개수 불일치 에러 방어 구역 시작] ------
                tags_list = []
                if "tags" in item and item["tags"]:
                    for tag in item["tags"]:
                        # 친구분이 작성한 MOCK처럼 원소가 6개짜리 튜플일 때 처리
                        if isinstance(tag, (list, tuple)) and len(tag) > 2:
                            # 의미 있는 텍스트만 추출해서 rtag로 감싸기
                            valid_tags = [str(x) for x in tag if str(x).strip() and str(x) not in ["acc", "loc"]]
                            for vt in valid_tags:
                                tags_list.append(f'<span class="rtag">{vt}</span>')
                        # 정상적인 2개짜리 (텍스트, 클래스) 구조일 때
                        elif isinstance(tag, (list, tuple)) and len(tag) == 2:
                            t, cls = tag
                            tags_list.append(f'<span class="rtag {cls}">{t}</span>')
                        # 그냥 문자열 하나만 들어있을 때
                        elif isinstance(tag, str):
                            tags_list.append(f'<span class="rtag">{tag}</span>')
                tags_html = "".join(tags_list)
                # ------ [🔥 튜플 개수 불일치 에러 방어 구역 끝] ------
                
                bar_w = item["score"]

                st.markdown(f"""
                <div class="result-card">
                  <div class="result-img">
                    {item["icon"]}
                    <div class="result-badge {badge_cls}">{item["score"]}% 일치</div>
                  </div>
                  <div class="result-body">
                    <div class="result-id">공고 {item["id"]}</div>
                    <div class="result-loc">📍 {item["loc"]} · {item["time"]} 발견</div>
                    <div class="result-tags">{tags_html}</div>
                    <div class="sim-row">
                      <div class="sim-bar-bg"><div class="sim-bar" style="width:{bar_w}%;"></div></div>
                      <div class="sim-pct">{bar_w}%</div>
                    </div>
                  </div>
                </div>
                """, unsafe_allow_html=True)
                if st.button("상세 보기 →", key=f"det_{i}", use_container_width=True):
                    st.session_state.selected = item
                    st.session_state.page = "detail"
                    st.rerun()

    elif st.session_state.page == "detail":
        item = st.session_state.selected
        bc1, bc2 = st.columns([1, 8])
        with bc1:
            if st.button("← 목록"):
                st.session_state.page = "results"
                st.rerun()
        with bc2:
            st.markdown(f'<div class="ss-page-title">공고 {item["id"]}</div>', unsafe_allow_html=True)
            st.markdown(f'<div class="ss-page-sub">CLIP 유사도 {item["score"]}% · {item["loc"]} · {item["time"]} 발견</div>', unsafe_allow_html=True)

        left, right = st.columns([2, 3])
        with left:
            pct = item["score"]
            st.markdown(f"""
            <div class="detail-panel">
              <div class="detail-img">
                {item["icon"]}
                <div class="detail-ai-badge">SafeSight · {pct}%</div>
                <div class="bbox-overlay"></div>
              </div>
              <div class="detail-body">
                <div class="detail-sim-label"><span>CLIP 유사도</span><span>{pct}%</span></div>
                <div class="detail-bar-bg"><div class="detail-bar" style="width:{pct}%;"></div></div>
                <div class="detail-grid">
                  <div class="detail-cell"><div class="dc-label">품종</div><div class="dc-value">{item["breed"]}</div></div>
                  <div class="detail-cell"><div class="dc-label">털 색상</div><div class="dc-value">{item["color"]}</div></div>
                  <div class="detail-cell"><div class="dc-label">착용 용품</div><div class="dc-value">{item["acc"]}</div></div>
                  <div class="detail-cell"><div class="dc-label">발견 위치</div><div class="dc-value">{item["loc"].split()[-1]}</div></div>
                </div>
                <div class="found-section">
                  <div class="found-title">발견 정보</div>
                  <div class="found-text">{item["detail"]}</div>
                </div>
                <div class="action-btns">
                  <div class="btn-primary">📞 보호소 연락하기</div>
                  <div class="btn-secondary">공유</div>
                </div>
              </div>
            </div>
            """, unsafe_allow_html=True)

        with right:
            st.markdown('<div class="ss-card">', unsafe_allow_html=True)
            st.markdown('<div class="ss-card-title">📊 유사 공고 비교</div>', unsafe_allow_html=True)
            for other in MOCK:
                if other["id"] != item["id"]:
                    bar_w = other["score"]
                    tags_html = "".join(f'<span class="rtag {cls}">{t}</span>' for t, cls in other["tags"])
                    st.markdown(f"""
                    <div style="display:flex;align-items:center;gap:14px;padding:12px 0;border-bottom:1px solid #EEF0F8;">
                      <div style="font-size:36px;">{other["icon"]}</div>
                      <div style="flex:1;">
                        <div style="font-size:12px;font-weight:700;color:#2E4BD6;">공고 {other["id"]}</div>
                        <div style="font-size:11px;color:#99A0B8;margin-bottom:5px;">{other["loc"]} · {other["time"]}</div>
                        <div class="result-tags">{tags_html}</div>
                      </div>
                      <div style="text-align:right;">
                        <div style="font-size:15px;font-weight:800;color:#12193A;">{other["score"]}%</div>
                        <div style="font-size:10px;color:#AAB2CC;">유사도</div>
                      </div>
                    </div>
                    """, unsafe_allow_html=True)
                    if st.button(f"보기 →", key=f"comp_{other['id']}"):
                        st.session_state.selected = other
                        st.rerun()
            st.markdown('</div>', unsafe_allow_html=True)

            st.markdown('<div class="ss-card" style="margin-top:16px;">', unsafe_allow_html=True)
            st.markdown('<div class="ss-card-title">🗺️ 발견 위치 정보</div>', unsafe_allow_html=True)
            st.markdown(f"""
            <div style="background:#F0F2FA;border-radius:10px;padding:16px;font-size:13px;color:#555;line-height:1.8;">
              <b>지역:</b> {item["loc"]}<br>
              <b>발견일:</b> {item["time"]}<br>
              <b>보호소:</b> {item["loc"].split()[0]} 유기동물 보호센터<br>
              <b>상태:</b> 보호 중
            </div>
            """, unsafe_allow_html=True)
            st.markdown('</div>', unsafe_allow_html=True)

    st.markdown('</div>', unsafe_allow_html=True)
